[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    Pragma = "no-cache"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache"
